### ISSUE TITLE
Need help, harp solver does not work on the last song

### ISSUE THREAD

**Issue by bobthejarfilebuilder** [AororiseSS/MelodyHairSolver#1]
All the other songs work but the last song only goes half way though before stopping. (I am using the latest version of harp solver) please fix i want the extra intelligence thank you.

**Comment by AororiseSS** [comment]
This has now been fixed in the latest latest thank you for supporting my mod. https://github.com/AororiseSS/MelodyHairSolver/releases/tag/V1.3
